"""empty message

Revision ID: 62a26825b8fa
Revises: 
Create Date: 2023-04-14 19:17:05.629496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a26825b8fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart3d_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cntl_file', sa.String(length=128), nullable=True),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('cbaero_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conf_file', sa.String(length=128), nullable=True),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpha_three_code', sa.String(length=3), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha_three_code'),
    sa.UniqueConstraint('icon')
    )
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('classification', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='tool_version_uk')
    )
    op.create_table('country_system_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_fk', sa.Integer(), nullable=False),
    sa.Column('country_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_fk'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['system_fk'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_system_associations_id'), 'country_system_associations', ['id'], unique=False)
    op.create_table('geometries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.Column('contributor_fk', sa.Integer(), nullable=False),
    sa.Column('system_fk', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['system_fk'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    op.create_table('tool_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cbaero_settings_fk', sa.Integer(), nullable=True),
    sa.Column('cart3d_settings_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart3d_settings_fk'], ['cart3d_settings.id'], ),
    sa.ForeignKeyConstraint(['cbaero_settings_fk'], ['cbaero_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cbaero_settings_fk', 'cart3d_settings_fk', name='tool_settings_uk')
    )
    op.create_table('configured_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_fk', sa.Integer(), nullable=False),
    sa.Column('tool_settings_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_fk'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['tool_settings_fk'], ['tool_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_fk', 'tool_settings_fk', name='tool_configuration_uk')
    )
    op.create_table('meshes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.Column('contributor_fk', sa.Integer(), nullable=False),
    sa.Column('geometry_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['geometry_fk'], ['geometries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    op.create_table('aero_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mach', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('lift_coefficient', sa.Float(), nullable=True),
    sa.Column('drag_coefficient', sa.Float(), nullable=True),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=False),
    sa.Column('mesh_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ),
    sa.ForeignKeyConstraint(['mesh_fk'], ['meshes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aero_results_id'), 'aero_results', ['id'], unique=False)
    op.create_table('tool_geometry_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributor_fk', sa.Integer(), nullable=False),
    sa.Column('geometry_fk', sa.Integer(), nullable=False),
    sa.Column('tool_fk', sa.Integer(), nullable=False),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['geometry_fk'], ['geometries.id'], ),
    sa.ForeignKeyConstraint(['tool_fk'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_mesh_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributor_fk', sa.Integer(), nullable=False),
    sa.Column('mesh_fk', sa.Integer(), nullable=False),
    sa.Column('tool_fk', sa.Integer(), nullable=False),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['mesh_fk'], ['meshes.id'], ),
    sa.ForeignKeyConstraint(['tool_fk'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=256), nullable=True),
    sa.Column('contributor_fk', sa.Integer(), nullable=True),
    sa.Column('system_fk', sa.Integer(), nullable=True),
    sa.Column('geometry_fk', sa.Integer(), nullable=True),
    sa.Column('mesh_fk', sa.Integer(), nullable=True),
    sa.Column('tool_mesh_association_fk', sa.Integer(), nullable=True),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['geometry_fk'], ['geometries.id'], ),
    sa.ForeignKeyConstraint(['mesh_fk'], ['meshes.id'], ),
    sa.ForeignKeyConstraint(['system_fk'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tool_mesh_association_fk'], ['tool_mesh_associations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('tool_mesh_associations')
    op.drop_table('tool_geometry_associations')
    op.drop_index(op.f('ix_aero_results_id'), table_name='aero_results')
    op.drop_table('aero_results')
    op.drop_table('meshes')
    op.drop_table('configured_tools')
    op.drop_table('tool_settings')
    op.drop_table('geometries')
    op.drop_index(op.f('ix_country_system_associations_id'), table_name='country_system_associations')
    op.drop_table('country_system_associations')
    op.drop_table('tools')
    op.drop_table('systems')
    op.drop_table('countries')
    op.drop_table('contributors')
    op.drop_table('cbaero_settings')
    op.drop_table('cart3d_settings')
    # ### end Alembic commands ###
