"""empty message

Revision ID: 6ac3480a3e90
Revises: 
Create Date: 2023-05-20 21:57:37.800653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac3480a3e90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart3d_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cntl_file', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cbaero_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conf_file', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpha_three_code', sa.String(length=3), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha_three_code'),
    sa.UniqueConstraint('icon')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='tool_version_uk')
    )
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('classification', sa.String(length=128), nullable=True),
    sa.Column('country_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_fk'], ['countries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=256), nullable=True),
    sa.Column('cbaero_settings_fk', sa.Integer(), nullable=True),
    sa.Column('cart3d_settings_fk', sa.Integer(), nullable=True),
    sa.CheckConstraint('(cbaero_settings_fk IS NULL) != (cart3d_settings_fk IS NULL)', name='tool_settings_check'),
    sa.ForeignKeyConstraint(['cart3d_settings_fk'], ['cart3d_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cbaero_settings_fk'], ['cbaero_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cbaero_settings_fk', 'cart3d_settings_fk', name='tool_settings_uk')
    )
    op.create_table('configured_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('tool_fk', sa.Integer(), nullable=False),
    sa.Column('tool_settings_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_fk'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['tool_settings_fk'], ['tool_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_fk', 'tool_settings_fk', name='tool_configuration_uk')
    )
    op.create_table('geometries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.Column('contributor_fk', sa.Integer(), nullable=False),
    sa.Column('system_fk', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_fk'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    op.create_table('meshes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.Column('contributor_fk', sa.Integer(), nullable=False),
    sa.Column('geometry_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_fk'], ['geometries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    op.create_table('tool_geometry_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributor_fk', sa.Integer(), nullable=False),
    sa.Column('geometry_fk', sa.Integer(), nullable=False),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_fk'], ['geometries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aero_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mach', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('lift_coefficient', sa.Float(), nullable=True),
    sa.Column('drag_coefficient', sa.Float(), nullable=True),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=False),
    sa.Column('mesh_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mesh_fk'], ['meshes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aero_results_id'), 'aero_results', ['id'], unique=False)
    op.create_table('aero_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('running', 'failed', 'succeeded', name='runstatus'), nullable=True),
    sa.Column('datetime_created', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('datetime_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contributor_fk', sa.Integer(), nullable=True),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=False),
    sa.Column('mesh_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mesh_fk'], ['meshes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aero_runs_id'), 'aero_runs', ['id'], unique=False)
    op.create_table('mass_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'failed', 'succeeded', name='runstatus'), nullable=True),
    sa.Column('trajectory_file', sa.String(length=128), nullable=True),
    sa.Column('mesh_fk', sa.Integer(), nullable=True),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=True),
    sa.Column('contributor_fk', sa.Integer(), nullable=True),
    sa.Column('datetime_created', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('datetime_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('results_file', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mesh_fk'], ['meshes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mass_estimates_id'), 'mass_estimates', ['id'], unique=False)
    op.create_table('tool_mesh_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributor_fk', sa.Integer(), nullable=False),
    sa.Column('mesh_fk', sa.Integer(), nullable=False),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['mesh_fk'], ['meshes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aero_run_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aero_result_fk', sa.Integer(), nullable=True),
    sa.Column('aero_run_fk', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('running', 'failed', 'succeeded', name='runstatus'), nullable=True),
    sa.ForeignKeyConstraint(['aero_result_fk'], ['aero_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['aero_run_fk'], ['aero_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aero_run_results_id'), 'aero_run_results', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=256), nullable=True),
    sa.Column('contributor_fk', sa.Integer(), nullable=True),
    sa.Column('system_fk', sa.Integer(), nullable=True),
    sa.Column('geometry_fk', sa.Integer(), nullable=True),
    sa.Column('mesh_fk', sa.Integer(), nullable=True),
    sa.Column('tool_setting_fk', sa.Integer(), nullable=True),
    sa.Column('configured_tool_fk', sa.Integer(), nullable=True),
    sa.Column('aero_run_fk', sa.Integer(), nullable=True),
    sa.Column('mass_estimate_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aero_run_fk'], ['aero_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['configured_tool_fk'], ['configured_tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_fk'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geometry_fk'], ['geometries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mass_estimate_fk'], ['mass_estimates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mesh_fk'], ['meshes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_fk'], ['systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_setting_fk'], ['tool_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_aero_run_results_id'), table_name='aero_run_results')
    op.drop_table('aero_run_results')
    op.drop_table('tool_mesh_associations')
    op.drop_index(op.f('ix_mass_estimates_id'), table_name='mass_estimates')
    op.drop_table('mass_estimates')
    op.drop_index(op.f('ix_aero_runs_id'), table_name='aero_runs')
    op.drop_table('aero_runs')
    op.drop_index(op.f('ix_aero_results_id'), table_name='aero_results')
    op.drop_table('aero_results')
    op.drop_table('tool_geometry_associations')
    op.drop_table('meshes')
    op.drop_table('geometries')
    op.drop_table('configured_tools')
    op.drop_table('tool_settings')
    op.drop_table('systems')
    op.drop_table('tools')
    op.drop_table('countries')
    op.drop_table('contributors')
    op.drop_table('cbaero_settings')
    op.drop_table('cart3d_settings')
    # ### end Alembic commands ###
